### ISSUE TITLE
Inngest server prints the Redis URI in the logs exposing passwords for Redis.

### ISSUE THREAD

**Issue by silwalanish** [inngest/inngest#2297]
**Describe the bug**
Inngest server prints the Redis URI in the logs exposing passwords for Redis.

https://github.com/inngest/inngest/blob/6b3941427fe18dece156db3fc8a64b5cff0fb71f/pkg/lite/lite.go#L389

**To Reproduce**
1. Start a redis server.
2. Run `inngest start --redis-uri=redis://:test%40123@redis:6379`

Docker Compose Example:

```yml
services:
  inngest-server:
    container_name: inngest-server
    image: "inngest/inngest:latest"
    command: "inngest start --redis-uri=redis://:test%40123@redis:6379"
    ports:
      - "8288:8288"

  redis:
    container_name: redis
    image: "redis:7.0.8-alpine3.17"
    command: 'redis-server --requirepass "test@123"'
    ports:
      - "6379:6379"
```

**Expected behavior**
Redis URI should not be printed.

**Screenshots / Stack trace dump**

```
inngest-server  | {"time":"2025-04-02T08:07:56.160450832Z","level":"INFO","msg":"creating user tracer"}
inngest-server  | {"time":"2025-04-02T08:07:56.160529696Z","level":"INFO","msg":"creating system tracer"}
inngest-server  | {"level":"info","time":"2025-04-02T08:07:56Z","message":"using external Redis redis://:test%40123@redis:6379; disabling in-memory persistence and snapshotting"}
inngest-server  | {"level":"info","caller":"persistence","time":"2025-04-02T08:07:56Z","message":"service starting"}
inngest-server  | {"level":"info","caller":"executor","time":"2025-04-02T08:07:56Z","message":"service starting"}
inngest-server  | {"level":"info","caller":"executor","time":"2025-04-02T08:07:56Z","message":"subscribing to function queue"}
inngest-server  | {"level":"info","caller":"runner","backend":"redis","time":"2025-04-02T08:07:56Z","message":"starting event stream"}
inngest-server  | {"level":"info","caller":"runner","time":"2025-04-02T08:07:56Z","message":"service starting"}
inngest-server  | {"level":"info","caller":"api","time":"2025-04-02T08:07:56Z","message":"service starting"}
inngest-server  | {"level":"info","caller":"api","caller":"api","addr":"0.0.0.0:8288","time":"2025-04-02T08:07:56Z","message":"starting server"}
inngest-server  | {"level":"info","caller":"runner","topic":"events","time":"2025-04-02T08:07:56Z","message":"subscribing to events"}
```
