### ISSUE TITLE
1.8.0 + self host + Postgres backend, boot failed and report: failed to init driver with path migrations/postgres: duplicate migration file: 000012_span_tables.down.sql

### ISSUE THREAD

**Issue by smoothdvd** [inngest/inngest#2604]
**Describe the bug**
Upgrade from 1.6.4/1.7.x to 1.8.0 with Postgres backend + self host using docker compose:

docker compose up and failed boot inngest in start mode, docker compose log is:

failed to init driver with path migrations/postgres: duplicate migration file: 000012_span_tables.down.sql

**To Reproduce**
1. Change docker image version to 1.8.0 from (1.6.x or 1.7.x)
2. docker compose up
3. boot failed

**Expected behavior**
Run 1.8.0 with Postgres end normally

**Screenshots / Stack trace dump**

**System info**
- inngest-cli version: [1.8.0]
- OS: [macOS]
- Version [15.5]

**Additional context**
compose.yaml:
```
  inngest:
    image: inngest/inngest:v1.8.0
    command: inngest start --event-key 7Aj1qOS6Bbb1WjvclgSpmRWVa5mU2nb4ILlNZArp+CXoKK5p --signing-key 12345 --postgres-uri postgres://strapi:strapi@postgres:5432/inngest_development --redis-uri redis://redis:6379
    ports:
      - 8288:8288
    restart: on-failure:0
    depends_on:
      - postgres
```
