### ISSUE TITLE
Go client with Inngest start command report error but event can be executed

### ISSUE THREAD

**Issue by smoothdvd** [inngest/inngest#2605]
**Describe the bug**
I develop app with Go SDK and create with
```
client, err := inngestgo.NewClient(inngestgo.ClientOpts{
	AppID: "kbase-production",
	Dev:   inngestgo.BoolPtr(false),
})
```
and Inngest server run with start command with docker compose
```
  inngest:
    image: inngest/inngest:v1.8.0
    command: inngest start --event-key 7Aj1qOS6Bbb1WjvclgSpmRWVa5mU2nb4ILlNZArp+CXoKK5p --signing-key 990b61800355c6c89f46222a1ea91928 --postgres-uri postgres://strapi:strapi@postgres:5432/inngest_development --redis-uri redis://redis:6379
    ports:
      - 8288:8288
    restart: on-failure:0
    depends_on:
      - postgre
```

Self host's dashboard's app manage page report app not sync but there are functions available in functions page and can be executed and showed monitor page. 

**To Reproduce**
1. Using Go SDK create client
2. Run Inngest server with docker compose
3. client app report:
2025/06/21 14:12:02 ERROR sync error error="error registering functions: Your signing key is invalid" syncKind=out_of_band
2025/06/21 14:12:02 ERROR error registering functions error="error registering functions: Your signing key is invalid"
4.client execute event no problem
 
**Expected behavior**
Go client app can be run without error report like TS client app with Inngest cli start command

**Screenshots / Stack trace dump**

<img width="885" alt="Image" src="https://github.com/user-attachments/assets/f52e2a53-d81f-46ad-95de-0957b69159c5" />

<img width="1164" alt="Image" src="https://github.com/user-attachments/assets/674a3670-1128-488a-8a71-2d76b00e7153" />

<img width="1482" alt="Image" src="https://github.com/user-attachments/assets/7d56eaec-8ed7-4a17-9e89-286cca71a0f3" />

**System info**
- inngest-cli version: [e.g. 1.7.1]
- OS: [e.g. macOS]
- Version [15.5]

**Additional context**
